version: 2

builds:
  - id: go-llm-lens
    main: ./cmd/server
    binary: go-llm-lens
    env:
      - CGO_ENABLED=0
    ldflags:
      - -X main.version={{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: checksums.txt

signs:
  - cmd: cosign
    args:
      - sign-blob
      - "--bundle=${artifact}.bundle"
      - "${artifact}"
      - "--yes"
    artifacts: all
    output: true
    signature: "${artifact}.bundle"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
